version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: nestjs-app
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    depends_on:
      db:
        condition: service_started
      migrate:
        condition: service_completed_successfully
    command: npm run start:dev

  migrate:
    build:
      context: .
      dockerfile: Dockerfile.migrate
    container_name: prisma-migrate
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    depends_on:
      db:
        condition: service_started
    command: npx prisma migrate deploy

  db:
    image: postgres:15
    container_name: postgres-db
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  node_modules: