/** Permission codes aligned with docs/client Table + RBAC.md */
export const PORTAL_PERMISSION_DEFS: ReadonlyArray<{ code: string; description: string }> = [
  { code: 'sales.create', description: 'Create a new sale' },
  { code: 'sales.view', description: 'View sales' },
  { code: 'sales.edit.client', description: 'Edit sales-stage client fields' },
  { code: 'sales.edit.product', description: 'Edit sales-stage product fields' },
  { code: 'sales.submit.accounts', description: 'Submit sale to accounts' },
  { code: 'accounts.view', description: 'View accounts stage' },
  { code: 'accounts.review', description: 'Review accounts stage' },
  { code: 'accounts.hold', description: 'Hold at accounts' },
  { code: 'accounts.approve', description: 'Approve accounts' },
  { code: 'accounts.reject', description: 'Reject at accounts' },
  { code: 'operations.view', description: 'View operations stage' },
  { code: 'operations.assign.device', description: 'Assign device / combo / SIM / accessories' },
  { code: 'operations.assign.technician', description: 'Assign technician user' },
  { code: 'operations.submit.technician', description: 'Hand off to technician stage' },
  { code: 'technician.view', description: 'View technician / installation data' },
  { code: 'technician.install.complete', description: 'Complete installation workflow' },
  { code: 'technician.install.edit', description: 'Edit installation fields' },
  { code: 'sales.reopen', description: 'Reopen a sale stage (admin)' },
  { code: 'sales.audit.view', description: 'View sale audit log' },
  { code: 'inventory.stores.view', description: 'View inventory stores' },
  { code: 'inventory.stores.create', description: 'Create inventory stores' },
  { code: 'inventory.stores.edit', description: 'Edit inventory stores' },
  { code: 'inventory.stores.delete', description: 'Delete inventory stores' },
  { code: 'inventory.categories.view', description: 'View inventory categories' },
  { code: 'inventory.categories.create', description: 'Create inventory categories' },
  { code: 'inventory.categories.edit', description: 'Edit inventory categories' },
  { code: 'inventory.categories.delete', description: 'Delete inventory categories' },
  { code: 'inventory.groups.view', description: 'View inventory groups' },
  { code: 'inventory.groups.create', description: 'Create inventory groups' },
  { code: 'inventory.groups.edit', description: 'Edit inventory groups' },
  { code: 'inventory.groups.delete', description: 'Delete inventory groups' },
  { code: 'inventory.vendors.view', description: 'View inventory vendors' },
  { code: 'inventory.vendors.create', description: 'Create inventory vendors' },
  { code: 'inventory.vendors.edit', description: 'Edit inventory vendors' },
  { code: 'inventory.vendors.delete', description: 'Delete inventory vendors' },
  { code: 'inventory.items.view', description: 'View inventory items' },
  { code: 'inventory.items.create', description: 'Create inventory items' },
  { code: 'inventory.items.edit', description: 'Edit inventory items' },
  { code: 'inventory.items.delete', description: 'Delete inventory items' },
  { code: 'inventory.items.bulk_create', description: 'Bulk create inventory items' },
  { code: 'inventory.pr.view', description: 'View purchase requests' },
  { code: 'inventory.pr.create', description: 'Create purchase requests' },
  { code: 'inventory.pr.edit', description: 'Edit purchase requests' },
  { code: 'inventory.pr.delete', description: 'Delete purchase requests' },
  { code: 'inventory.pr.approve', description: 'Approve purchase requests' },
  { code: 'inventory.pr.reject', description: 'Reject purchase requests' },
  { code: 'inventory.po.view', description: 'View purchase orders' },
  { code: 'inventory.po.create', description: 'Create purchase orders' },
  { code: 'inventory.po.edit', description: 'Edit purchase orders' },
  { code: 'inventory.po.delete', description: 'Delete purchase orders' },
  { code: 'inventory.po.approve', description: 'Approve purchase orders' },
  { code: 'inventory.po.reject', description: 'Reject purchase orders' },
  { code: 'inventory.grn.view', description: 'View goods receiving notes' },
  { code: 'inventory.grn.create', description: 'Create goods receiving notes' },
  { code: 'inventory.grn.edit', description: 'Edit goods receiving notes' },
  { code: 'inventory.grn.delete', description: 'Delete goods receiving notes' },
  { code: 'inventory.grn.confirm', description: 'Confirm goods receiving notes' },
  { code: 'inventory.issuance.view', description: 'View issuance records' },
  { code: 'inventory.issuance.create', description: 'Create issuance records' },
  { code: 'inventory.issuance.edit', description: 'Edit issuance records' },
  { code: 'inventory.issuance.delete', description: 'Delete issuance records' },
  { code: 'inventory.issuance.bulk_create', description: 'Bulk create issuance records' },
  { code: 'inventory.returns.view', description: 'View returns records' },
  { code: 'inventory.returns.create', description: 'Create returns records' },
  { code: 'inventory.returns.edit', description: 'Edit returns records' },
  { code: 'inventory.returns.delete', description: 'Delete returns records' },
  { code: 'inventory.transfers.view', description: 'View transfer records' },
  { code: 'inventory.transfers.create', description: 'Create transfer records' },
  { code: 'inventory.transfers.edit', description: 'Edit transfer records' },
  { code: 'inventory.transfers.delete', description: 'Delete transfer records' },
  { code: 'inventory.stock.view', description: 'View inventory card / stock ledger' },
  { code: 'inventory.reports.stock', description: 'View stock report' },
  { code: 'inventory.reports.issuance', description: 'View issuance report' },
  { code: 'inventory.reports.returns', description: 'View returns report' },
  { code: 'inventory.reports.transfers', description: 'View transfers report' },
  { code: 'inventory.reports.purchase', description: 'View purchase report' },
  { code: 'inventory.utility.view', description: 'View utility dropdowns and searches' },
  { code: 'inventory.dashboard.view', description: 'View dashboard stats' },
  { code: 'inventory.dashboard.lowstock', description: 'View low-stock items' },
  { code: 'inventory.dashboard.outofstock', description: 'View out-of-stock items' },
] as const;

export const PORTAL_PERMISSION_CODES = PORTAL_PERMISSION_DEFS.map((p) => p.code);

export const PERMISSIONS_METADATA_KEY = 'portal:permissions';

export type PermissionRequirement = {
  codes: string[];
  mode: 'any' | 'all';
};
