name: Sync to Secondary Repo

on:
  push:
    branches:
      - main   # change to master if your main branch is master

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main repo
        uses: actions/checkout@v3

      - name: Push to secondary repo
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"

          git remote add secondary https://x-access-token:${{ secrets.SYNC_TOKEN }}@github.com/fayzan101/crescent-be.git
          git push secondary HEAD:main --force