name: Sync to Second Repo

on:
  push:
    branches:
      - master

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repo
        uses: actions/checkout@v3

      - name: Push to second repo
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"

          git clone https://x-access-token:${{ secrets.SYNC_TOKEN }}@github.com/fayzan101/crescent-be.git target

          rsync -av --delete --exclude='.git' ./ target/

          cd target
          git add .
          git commit -m "Auto sync from main repo" || echo "No changes"
          git push origin main
